spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rolly-database1.c3vnkyvz16i6.ap-southeast-2.rds.amazonaws.com:3306/rollydatabase1?&useSSL=false&serverTimezone=UTC
    username: ky7662
    password: yyang011!

  jpa:
    database: mysql
    hibernate.ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: AKIA3FGIJEEOCN5DYKGJ
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: rollyawsbuket
    stack:
      auto: false

application:
  bucket:
    name: rollyawsbuket //버킷이름

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

my:
  property:
    name: Hello, World!